# Generated by Django 2.2 on 2019-07-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFirst', '0003_auto_20190716_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='descricao',
            new_name='produto',
        ),
    ]
